baseURL = "https://alix.anneraud.fr"
theme = "gokarna"
title = "Alix ANNERAUD"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableEmoji = true
enableRobotsTXT = true

[languages]
    [languages.fr]
        languageCode = "fr-FR"
        disabled = false
        langageDirection = "ltr"
        contentDir = "content/French"
        langageName = "Français"
        weight = 2
        [langage.fr.params]
            description = "Etudiant salarié à l'INSA de Rouen Normandie en spécialité Informatique et Technologies de l'Information."
    [languages.en]
        languageCode = "en-US"
        disabled = false
        langageDirection = "ltr"
        contentDir = "content/English"
        langageName = "English"
        weight = 1
        [langage.en.params]
            description = "Student at INSA Rouen Normandie in Computer Science and Information Technology."

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Alix ANNERAUD"
  avatarURL = "/images/avatar.webp"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "github", url = "https://github.com/AlixANNERAUD"},
    {name = "email", url = "mailto:alix@anneraud.fr"},
    {name = "linkedin", url = "https://www.linkedin.com/in/alix-anneraud/"}
  ]
  metaKeywords = ["portfolio", "alix", "anneraud", "insa"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "french"
    pre = "🇫🇷"
    url = "/fr/"
    weight = 8

    [[menu.main]]
    identifier = "english"
    pre = "🇬🇧"
    url = "/en/"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
