name: Update statistics cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: profile/statistics.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=10&size_weight=0.5&count_weight=0.5
          path: profile/top-languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Wakatime card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: username=alix_anneraud&api_domain=wakapi.anneraud.fr

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: profile

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
